# coding=UTF-8
#
# generate the LaTeX commands to produce Tetris characters where I want them
# for Cross Stitch Tetris kits
#
# mmcgaley@gmail.com
# 2015.08.12
#

def printS(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY-4)
   printBlock(startX-4, startY-4)
   printBlock(startX+4, startY)

def printS_2(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY-4)
   printBlock(startX+4, startY-4)
   printBlock(startX-4, startY)

def printZ(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY-4)
   printBlock(startX+4, startY-4)
   printBlock(startX-4, startY)

def printZ_2(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY-4)
   printBlock(startX-4, startY-4)
   printBlock(startX+4, startY)

def printT(startX, startY) :
   printBlock(startX,startY)
   printBlock(startX+4,startY)
      printBlock(startX+8,startY)
   printBlock(startX+4,startY+4)

def printI(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX+4, startY)
   printBlock(startX+8, startY)
   printBlock(startX+12, startY)

def printO(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY+4)
   printBlock(startX+4, startY)
   printBlock(startX+4, startY+4)

def printL(startX, startY) :
   printBlock(startX, startY)
   printBlock(startX, startY-4)
   printBlock(startX+4, startY)
   printBlock(startX+8, startY)

def printJ(startX, startY) :
   printBlock(startX,startY)
   printBlock(startX+4,startY)
   printBlock(startX+8,startY)
   printBlock(startX+8,startY-4)


def printBlock(startX, startY) :
   # light gray upper left squares

   print "% block starting at ", startX, ",", startY
   print "% light gray squares top row then left side"
   print "\\filldraw[fill=lightgray] (",startX,",",startY,") rectangle (",startX+1,",",startY-1,");"
   print "\\filldraw[fill=lightgray] (",startX+1,",",startY,") rectangle (",startX+2,",",startY-1,");"
   print "\\filldraw[fill=lightgray] (",startX+2,",",startY,") rectangle (",startX+3,",",startY-1,");"
      print "\\filldraw[fill=lightgray] (",startX,",",startY-1.1,") rectangle (",startX+1,",",startY-2,");"
   print "\\filldraw[fill=lightgray] (",startX,",",startY-2.1,") rectangle (",startX+1,",",startY-3,");"

   # gray others
   print "% mid-gray squares row by row"
   print "\\filldraw[fill=gray] (",startX+3,",",startY,") rectangle (",startX+4,",",startY-1,");"

   print "\\filldraw[fill=gray] (",startX+1,",",startY-1.1,") rectangle (",startX+2,",",startY-2,");"
   print "\\filldraw[fill=gray] (",startX+2,",",startY-1.1,") rectangle (",startX+3,",",startY-2,");"
   print "\\filldraw[fill=gray] (",startX+3,",",startY-1.1,") rectangle (",startX+4,",",startY-2,");"

   print "\\filldraw[fill=gray] (",startX+1,",",startY-2.1,") rectangle (",startX+2,",",startY-3,");"
   print "\\filldraw[fill=gray] (",startX+2,",",startY-2.1,") rectangle (",startX+3,",",startY-3,");"
   print "\\filldraw[fill=gray] (",startX+3,",",startY-2.1,") rectangle (",startX+4,",",startY-3,");"

   print "\\filldraw[fill=gray] (",startX,",",startY-3.1,") rectangle (",startX+1,",",startY-4,");"
   print "\\filldraw[fill=gray] (",startX+1,",",startY-3.1,") rectangle (",startX+2,",",startY-4,");"
   print "\\filldraw[fill=gray] (",startX+2,",",startY-3.1,") rectangle (",startX+3,",",startY-4,");"
   print "\\filldraw[fill=gray] (",startX+3,",",startY-3.1,") rectangle (",startX+4,",",startY-4,");\n"

# 
print "% LaTeX document for Tetris Cross Stitch kit by Margaret Synnott"
print "% see tetris.timui.org"
print "% generated by generate_pieces.py\n"
print "\documentclass[a4paper,12pt]{article}"
print "\usepackage{tikz}"
print "\usepackage[margin=2cm]{geometry}"
print "\usepackage{fancyhdr}"
print "\pagestyle{fancy}"
print "\\addtolength{\headheight}{\\baselineskip}"
print "\lhead{timui.org}"
print "\\rhead{Tetris Counted Cross Stitch}"
print "\\rfoot{tetris.timui.org}"


print "\\begin{document}"
print "\\pagenumbering{gobble}%"

print "\nTetris has 7 different tetrominoes sometimes referred to using"
print "letters they resemble. Here is a counted cross"
print "stitch chart of all the shapes:" 
print "\\vspace{1em}\n"
print "\\begin{center}"
print "\\begin{tikzpicture}[x=2mm,y=2mm]"
print "\\draw[step=2mm,gray,very thin] (-20,-3) grid (9,30);"


# S
print "\n%\n% S shaped tetris\n%\n"
print "\\node at (-21, 27) {S};\n"
printS(-15,29)

# Z
print "\n%\n% Z shaped tetris\n%\n"
print "\\node at (-21, 18) {Z};\n"
printZ(-15,20)

# T
print "\n%\n% T shaped tetris\n%\n"
print "\\node at (-21, 9) {T};\n"
printT(-19,7)

# O
print "\n%\n% O shaped tetris\n%\n"
print "\\node at (10, 27) {O};\n"
printO(-4,25)

# L
print "\n%\n% L shaped tetris\n%\n"
print "\\node at (10, 18) {L};\n"
printL(-4,20)

# J
print "\n%\n% J shaped tetris\n%\n"
print "\\node at (10, 9) {J};\n"
printJ(-4,11)

# I
print "\n%\n% I shaped tetris\n%\n"
print "\\node at (-21, 0) {I};\n"
printI(-19,2)

print "\\end{tikzpicture}\n"
print "\\vspace{1em}\n"
print "\\end{center}"

print "\nThe kit includes a pair of coloured threads for each of the 7 shapes."
print "The darker colour fills most of the shape,"
print "with the paler colour in the corner to give a 3D effect (as shown"
print "above). I'll leave it up to you to choose colours for the shapes."
print "I suggest you write your colour selection onto the thread-card. You may"
print "also like to redraw the pattern with coloured pencils. I have included"
print "a squared page for this purpose.\n"

print "Here is a suggested arrangement for the tetrominoes. The player is just"
print "about to complete a Tetris, which I find very satisfying :)\n"

print "\\vspace{1em}\n"
print "\\begin{center}"
print "\\begin{tikzpicture}[x=2mm,y=2mm]"
print "\\draw[step=2mm,gray,very thin] (0,0) grid (50,45);"
# bottom row
# T
#printT(1,5)
# J
#printJ(9,9)

print "\\end{tikzpicture}"
print "\\end{center}"
print "\\vspace{1em}\n"

print "If you design your own, don't forget to leave at least one empty spot"
print "per row.  If the row was complete it would have been cleared away!"
print "And don't forget that when you rotate the shapes the lighter colour"
print "should always be in the top left corner.\n"

print "\end{document}"
